### ISSUE TITLE
This template doesn't work at all 

### ISSUE THREAD

**Issue by nemethmik** [lit/lit-element-starter-ts#58] opened 2021-09-14 13:13 UTC
Hello,
I am new fan of Lit, lit element and lit-html, and I found this template yesterday as a TypeScript project starter.
Here is a video I have recorded [Lit Element Starter TS Doesn't Work at All - Terribly Disappointing](https://youtu.be/86tet76u0uk)
I was really hesitant to share my experience, but may be you are interested. Regard it as a contribution.
If you think this is not relevant as an Open Issue, just delete it.
Thank you and all the best,
Miklos

**Comment by maitrungduc1410** [comment] 2021-10-01 07:37
Agree

**Comment by obeka** [comment] 2021-10-01 10:53
I tried to use the TypeScript kit, but couldn't understand how to change the content of my-element.ts . I am changing the return html string like adding additional button and then run `npm run build` and then `npm run serve`, everything is same. The documentation is too weak.

**Comment by AndrewJakubowicz** [comment] 2021-11-15 17:32
Hi @nemethmik! Thank you for opening this issue. You identified a bug in the starter kits where they would serve documentation with `npm run serve` instead of your component.

This should be addressed after [this change](https://github.com/lit/lit/commit/8b9dcb4d10e4161083146ae40d0b12174a63d31d) is released.

That change makes it more straight forward to get a browser page with the example running without requiring figuring out urls or imports as you had to in the video.

I'll follow up on this thread once the starter kits have had a new release.
Thank you!

**Comment by AndrewJakubowicz** [comment] 2021-12-08 23:12
Sorry for the slow turnaround. Now that https://github.com/lit/lit-element-starter-ts/commit/43c1dfb1c9444ca621aced60640e5bd8dfa36182 has been merged the experience should be improved. Please take a look and let me know if some of these critical issues have been addressed.

Thank you!

**Comment by wilberforce** [comment] 2021-12-13 23:03
@AndrewJakubowicz 

> Please take a look and let me know if some of these critical issues have been addressed.

no. It does not build.

```
> @lit/lit-starter-ts@1.0.0 build
> tsc

../../../../node_modules/.pnpm/@types+jest@26.0.23/node_modules/@types/jest/index.d.ts:35:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'HookFunction', but here has type 'Lifecycle'.

35 declare var beforeEach: jest.Lifecycle;
               ~~~~~~~~~~

  node_modules/.pnpm/@types+mocha@9.0.0/node_modules/@types/mocha/index.d.ts:2624:13
    2624 declare var beforeEach: Mocha.HookFunction;
                     ~~~~~~~~~~
    'beforeEach' was also declared here.

../../../../node_modules/.pnpm/@types+jest@26.0.23/node_modules/@types/jest/index.d.ts:37:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'afterEach' must be of type 'HookFunction', but here has type 'Lifecycle'.

37 declare var afterEach: jest.Lifecycle;
               ~~~~~~~~~
```

**Comment by AndrewJakubowicz** [comment] 2021-12-14 03:54
Thanks for the comment! I can't seem to reproduce the `npm run build` error that you have linked and need some additional repro steps.

I did the following. Cloned a new starter template and ran `npm install` and `npm run build`. Also tested `npm run docs`. Ran them a couple times to see if there was an ordering issue and everything seems to work.

Looking over the dependencies and transient dependencies the starter kit shouldn't include `@types/jest` and only includes `@types/mocha`. I don't know enough about `pnpm` to check how/where the jest types could be coming from.

My Environment:

Mac Monterey

```bash
$ npm --version
8.1.3
$ node -v
v16.5.0
```

**Comment by wilberforce** [comment] 2021-12-14 04:14
@AndrewJakubowicz - Thanks

> I don't know enough about `pnpm` to check how/where the jest types could be coming from.

I think this now an pnpm issue - then `tsc` is called it's using the pnpm installed version rather than the local npm version.

I'm on npm 8.1.0 and node 17.0.0

You can probably close this out.

Thanks

**Comment by wilberforce** [comment] 2021-12-14 04:36
I got this to build using my F: drive rather than c: drive and got the build to work.... so does seems to be pnpm related.

**Comment by AndrewJakubowicz** [comment] 2021-12-15 01:10
Closing as the broken url serving highlighted in the linked video has been addressed.

**Closed by AndrewJakubowicz** 2021-12-15 01:10 UTC
